[package]
name = "silver"
edition = "2024.beta"
license = "MIT"
authors = ["Satyam Bansal (satyamsgsits1994@gmail.com)"]

[dependencies]

Sui = { git = "https://github.com/MystenLabs/sui.git", rev = "9c04e1840eb5", subdir = "crates/sui-framework/packages/sui-framework" }


[addresses]
silver = "0x0"


[dev-dependencies]

[dev-addresses]
