[package]
name = "swap_contract"
edition = "2024.beta"
license = "MIT"
authors = ["Satyam Bansal (satyamsgsits1994@gmail.com)"]

[dependencies]


[addresses]
swap_contract = "0x0"


[dev-dependencies]

[dev-addresses]
